config/routes.rb
Neo4jExample::Application.routes.draw do
  resources :users do
    get :add_friend
    get :remove_friend
  end

  root 'users#index'

end

app/models/user.rb
require 'rubygems'
require 'neography'
require 'active_model'

class User 
  include ActiveModel::Model
  @neo = Neography::Rest.new
  attr_accessor :name, :node

  def self.all
    users = []
    response = @neo.execute_query("START n=node(*) WHERE n.type='user' RETURN n;")
    response["data"].each do |data|
      user = data[0]["data"]
      user["id"] = data[0]["self"].split('/').last
      users << user
    end
    users
  end

  def self.find(id)
    new(node: Neography::Node.load(id))
  end


  def save
    neo.create_node(name: name, type: 'user')
  end

  def neo
    @neo || Neography::Rest.new
  end

  def friends
    self.node.outgoing(:friends)
  end

  def self.add_friend(user_id, friend_id)
    friend = Neography::Node.load(friend_id)
    user = Neography::Node.load(user_id)
    @neo.create_relationship("friends", user, friend)
  end

  def unfriend(friend_id)
    neo.get_node_relationships(self.node, "out", "friends").each do |rel|
      if rel['end'].split('/').last  == friend_id
        neo.delete_relationship(rel['self'].split('/').last)
        break
      end
    end
  end

  def suggested_friends
    users, friend_ids = [], [self.node.neo_id.to_i]
    self.friends.each{|f| friend_ids << f.neo_id.to_i}
    response = neo.execute_query("START n=node(*) WHERE NOT (ID(n) IN #{friend_ids}) AND n.type='user' RETURN n;")
    response["data"].each do |data|
      user = data[0]["data"]
      user["id"] = data[0]["self"].split('/').last
      users << user
    end
    users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ObjectifyParams
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @user = User.find(8177)
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user, notice: 'User was successfully created.'
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  def add_friend
    User.add_friend(params[:user_id], params[:friend_id])
    redirect_to users_path
  end

  def remove_friend
    user = User.find(params[:user_id])
    user.unfriend(params[:friend_id])
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neo4jExample</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Hello <%= @user.node.name%></h1>
<br />
<h2><%= @user.node.name%> 's Friends</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <% @user.friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= link_to 'Unfriend', user_remove_friend_path(@user.node.neo_id, friend_id: friend.neo_id), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<h2>Suggested Friends</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <% @user.suggested_friends.each do |friend| %>
      <tr>
        <td><%= friend["name"] %></td>
        <td><%= link_to 'Add as Friend', user_add_friend_path(@user.node.neo_id, friend_id: friend["id"]), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user["name"] %>
</p>

<%= link_to 'Edit', edit_user_path(@user["id"]) %> |
<%= link_to 'Back', users_path %>